apiVersion: v1
kind: Service
metadata:
  name: finoku-news-panel-service
spec:
  selector:
    app.kubernetes.io/name: finoku-news-panel-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9378
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9379