apiVersion: apps/v1
kind: Deployment
metadata:
  name: finoku-news-panel-deployment
spec:
  replicas: 3  # Adjust the desired number of replicas
  selector:
    matchLabels:
      app: finoku-news-panel
  template:
    metadata:
      labels:
        app: finoku-news-panel
    spec:
      containers:
      - name: finoku-news-website
        image: finoku-news-panel:latest
        ports:
        - containerPort: 443
      - name: liveness
      image: registry.k8s.io/busybox
      args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5