apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: finoku-blog-database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finoku-blog-database
  serviceName: finoku-blog-database
  template:
    metadata:
      labels:
        app: finoku-blog-database
  spec:
    containers:
    - name: mongodb
      image: mongo:latest
      ports: 
      - containerPort: 27017
      volumeMounts:
      - name: mongodb-persistent-storage
        mountPath: /data/db
    volumes:
    - name: mongodb-persistent-storage