apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      automountServiceAccountToken: false
      containers:
      - name: redis
        image: redis:latest
        command: ["redis-server", "/data/redis.conf"]
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "512m"
            memory: "1Gi"
          requests:
            cpu: "1Gi"
            memory: "2Gi"
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pvc