apiVersion: v1
kind: Service
metadata:
  name: finoku-blog-admin-website-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9380
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9381