apiVersion: apps/v1
kind: Deployment
metadata:
  name: finoku-news-admin-website-deployment
spec:
  replicas: 3  # Adjust the desired number of replicas
  selector:
    matchLabels:
      app: finoku-news-admin-website
  template:
    metadata:
      labels:
        app: finoku-news-admin-website
    spec:
      containers:
      - name: finoku-news-admin-website
        image: finoku-news-admin-website:latest
        ports:
        - containerPort: 443