apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.15.0
        resources:
          limits:
            cpu: 1Gi
          requests:
            cpu: 100m
        env:
          - name: LOGSTASH_URL
            value: http://logstash:5601
        ports:
        - containerPort: 5044
      - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5